version: '3.8'

services:
  mongo:
    container_name: myfilmes-mongo-development
    image: mongo
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: senhaS3creta

  mongo-express:
    container_name: myfilmes-mongo-express-development
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: senhaS3creta
      ME_CONFIG_MONGODB_URL: mongodb://root:senhaS3creta@mongo:27017/
        
  redis:
    container_name: myfilmes-redis-development
    image: redis:latest
    hostname: localhost
    ports:
        - 6379:6379
  
  rabbitmq:
    container_name: myfilmes-rabbitmq-development
    image: rabbitmq:3-management
    hostname: localhost
    ports:
        - 5672:5672
        - 15672:15672